apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: offlinesessionses.dex.coreos.com
  labels:
    app.kubernetes.io/name: dex
spec:
  group: dex.coreos.com
  version: v1
  names:
    plural: offlinesessionses
    singular: offlinesessions
    kind: OfflineSessions
