apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
  labels:
    app.kubernetes.io/name: dex
spec:
  group: dex.coreos.com
  version: v1
  names:
    plural: passwords
    singular: password
    kind: Password
