apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
  labels:
    app.kubernetes.io/name: dex
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: dex.coreos.com
  version: v1
  names:
    plural: passwords
    singular: password
    kind: Password
