apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: signingkeies.dex.coreos.com
  labels:
    app.kubernetes.io/name: dex
spec:
  group: dex.coreos.com
  version: v1
  names:
    plural: signingkeies
    singular: signingkey
    kind: SigningKey
